### ISSUE TITLE
Matcha theme on gnome 3.36 font issue

### ISSUE THREAD

**Issue by Alexander-Huang** [vinceliuice/Matcha-gtk-theme#100]
Under gnome3.36, Matcha's English font behaves like full-width, and the Chinese display is normal. I have tried switching between several fonts or restarting the shell, but nothing worked.
![2020-03-20 11-24-53 的屏幕截图](https://user-images.githubusercontent.com/42209822/77133330-b1958f80-6a9d-11ea-911c-8965cfd0d7bf.png)
Archlinux，gnome3.36

**Comment by vinceliuice** [comment]
你用的什么字体啊

**Comment by Alexander-Huang** [comment]
> 你用的什么字体啊

wow,so fast
我用的noto-sans-cjk-sc（思源黑体），但是我切换成了wqy-microhei这个问题也存在

**Comment by vinceliuice** [comment]
系统自带的字体呢，像cantarell，Noto-sans这些字体有问题吗

**Comment by Alexander-Huang** [comment]
> 系统自带的字体呢，像cantarell，Noto-sans这些字体有问题吗

试了一下，还是有一样的问题。如果我换斜体的话，字体也会倾斜，但还是像上面那样。
Vimix的gnome-shell主题也有这个问题，Adapta和Arc主题正常。
然后我试过了从github直接clone和从AUR安装，都有同样的问题。

**Comment by vinceliuice** [comment]
那应该是主题的问题，我回去测试一下，试着把这个问题修复了

**Comment by Alexander-Huang** [comment]
> 那应该是主题的问题，我回去测试一下，试着把这个问题修复了

谢谢大佬。但是我看到另一个issue里字体就是正常的，会不会是我少装了什么？
但是_common.scss里面的字体我都装齐了

**Comment by Alexander-Huang** [comment]
哦不对，他用的是英语，可能不是utf8

**Comment by vinceliuice** [comment]
最新版的gnome-shell默认主题把font-family去掉了，或许我也应该把这个去掉

**Comment by Alexander-Huang** [comment]
> 最新版的gnome-shell默认主题把font-family去掉了，或许我也应该把这个去掉

大佬加油

**Comment by vinceliuice** [comment]
好的，谢谢！

**Comment by vinceliuice** [comment]
你试试最新版还有这个问题吗

**Comment by Alexander-Huang** [comment]
> 你试试最新版还有这个问题吗

谢谢大佬，已经没有任何问题了！

**Comment by vinceliuice** [comment]
好的
