### ISSUE TITLE
Visual issue in gnome-polkit

### ISSUE THREAD

**Issue by Ste74** [vinceliuice/Matcha-gtk-theme#101]
As you can see we have an issue with gnome-polkit.
![immagine](https://user-images.githubusercontent.com/11218234/77232809-839a7300-6ba3-11ea-9bc2-f84351fec3c5.png)
OS Manjaro gnome unstable
We use your last commit made some hours ago.

Stefano

**Comment by vinceliuice** [comment]
Issue fixed now!

**Comment by Ste74** [comment]
Thank you for the fastest response :+1:
