### ISSUE TITLE
A few bugs in matcha-aliz theme. version 20200324

### ISSUE THREAD

**Issue by algent-al** [vinceliuice/Matcha-gtk-theme#103]
**Additional Info**

- Matcha-gtk-theme version:  20200324
- GTK3 version: 3.24.14
- Distribution (and version): Solus Fortitude 4.1
- Desktop environment (and version): Budgie 10.5.1
- Related application (and version): Nautilus 3.26.4

**Issues**

Issue 1. Nautilus background is transparent in matcha-aliz theme.

![matcha-aliz-bug](https://user-images.githubusercontent.com/46356616/77426344-98118200-6dd4-11ea-93a1-5d0cdcec2a25.gif)

Issue 2. Text color in desktop should be white instead of black.
**matcha-aliz**
![text-color-desktop](https://user-images.githubusercontent.com/46356616/77427590-f3447400-6dd6-11ea-91e9-975a372c35ce.png) 

**matcha-azul** which is OK
![matcha-azul-theme](https://user-images.githubusercontent.com/46356616/77427694-1a9b4100-6dd7-11ea-91d4-dcd85354faf4.png)

Issue 3. Dot not vizible in below icons in panel
**matcha-aliz**
![matcha-aliz-panel](https://user-images.githubusercontent.com/46356616/77428086-d2305300-6dd7-11ea-925c-0445ea6e0002.png)

**matcha-aliz** panel size increased to 71
![matcha-aliz-panel-71](https://user-images.githubusercontent.com/46356616/77428174-0277f180-6dd8-11ea-99b7-d1e4d7a42ccd.png)

**matcha-azul** OK
![matcha-azul-panel](https://user-images.githubusercontent.com/46356616/77428120-e5dbb980-6dd7-11ea-8b08-1c988c0cd1b8.png)

**Steps to Reproduce**

1. Switch system theme to "Matcha-aliz*"

**Comment by philmmanjaro** [comment]
**20200324** is optimized for **Gnome 3.36**. For **3.34** you may want to use an older version of this theme.

**Comment by algent-al** [comment]
Hi @philmmanjaro !
Solus use Gnome 3.36 too, but I can't test this theme on Gnome for now. I am using Budgie Desktop. This issue is only for "Matcha-aliz" variant. All other 8 variants are OK.

**Comment by algent-al** [comment]
Matcha-aliz from pling is working fine. I forgot to mention that i have this problem with Matcha-aliz builded from source.

**Comment by algent-al** [comment]
Maybe i am wrong but I think the issue started from [here](https://github.com/vinceliuice/Matcha-gtk-theme/commit/c4322ae3122943616dab8ccad2eeda4aee0214ba).

There are  5,955 changes to src/gtk-3.0/gtk-aliz.css.
![matcha](https://user-images.githubusercontent.com/46356616/77801299-df1fa180-7078-11ea-90ea-fdef07bff758.png)

Buiild the theme from that commit "c4322ae3122943616dab8ccad2eeda4aee0214ba".
Found that the issue is still there.

**Comment by vinceliuice** [comment]
Fixed

**Comment by algent-al** [comment]
Thank you! I confirm that last commit fixed the issue.
