### ISSUE TITLE
Changes in gtk-aliz.css break text selection highlighting in Firefox

### ISSUE THREAD

**Issue by z3nbum** [vinceliuice/Matcha-gtk-theme#104]
Matcha-gtk-theme version: 2020-03-24
GTK3 version: 3.24.14
Gnome version: 3.36.0
Firefox version: 74.0
Manjaro Linux version: 19.0.2

Steps to reproduce:
1. Set system theme to Matcha-aliz.
2. Run Firefox, select Default (Light) Firefox theme.
3. In Firefox, display a web page and select some text.

Expected behavior:
Selection should be displayed as white text with a red background.

Actual behavior:
Selection remains black text with a white background. On close inspection, one can see that the text changes very subtly to a slightly lighter shade of gray.

Workaround:
Replace  src/gtk-3.0/gtk-aliz.css with the corresponding file from version 2020-03-15.

Notes:
1. I haven't noticed any similar text selection problems in any other apps. In particular, the Brave, Chromium, and Epiphany browsers seem to work fine.
2. With system theme set to either Matcha-azul or Matcha-sea, text selection in Firefox works as expected. I notice that about 5,900 lines were changed in gtk-aliz.css, mostly deletions; whereas about 2,200 lines were changed in gtk-azul.css and gtk-sea.css, with roughly equal numbers of additions and deletions. Naively, I would think all three files should have similar changes, with only color codes being different between them (but then, I know only enough about CSS to be dangerous).

**Comment by vinceliuice** [comment]
Fixed

**Comment by z3nbum** [comment]
Have just started using the new  src/gtk-3.0/gtk-aliz.css file and so far it looks like it is indeed fixed.
Thank you.
