### ISSUE TITLE
Light top bar

### ISSUE THREAD

**Issue by mcnesium** [vinceliuice/Matcha-gtk-theme#106]
I am trying to make the top bar light. On https://github.com/vinceliuice/Matcha-gtk-theme/commit/e2b14e517286a8b33bc7c08801568e89c0a61ec7 I edited `_colors.scss` [here](https://github.com/vinceliuice/Matcha-gtk-theme/blob/e2b14e517286a8b33bc7c08801568e89c0a61ec7/src/gnome-shell/sass/_colors.scss#L42):

    -$topbar_color: #1b2224;
    +$topbar_color: #FAFAFA;

Then I did `./install.sh -n matcha-mcn -t sea` and chose "Matcha-mcn-light-sea" in `Tweaks / Appearance / Shell`. Switched back and forth a few times, reloaded the Gnome Shell using `Alt+F2 – r`. Still, the top bar is dark :disappointed:

According to the color picker it is still the original value `#1B2224`. Why is it not changing? 
This is on Manjaro Gnome 3.36.0 X11. I had this working with Gnome 3.34. Did something change there?

**Comment by vinceliuice** [comment]
After you edit the scss files you need run ./parse-sass.sh first
