### ISSUE TITLE
Nemo side panel always dark, causes icon legibility issues

### ISSUE THREAD

**Issue by Magean0** [vinceliuice/Matcha-gtk-theme#107]
First of all, thanks for your incredible work on all your themes. You elevate Linux theming into a true art.

When using Nemo file manager, the side panel is always dark, even with Matcha Light (latest git version). Not only does that look a bit odd on an otherwise light theme, but icon legibility is affected when the side panel is on Tree View mode. See the following screenshots (one with Qogir icons, the other with Papirus): https://imgur.com/a/5jSS7Wz

With your Qogir icon theme, devices are clearly visible but the home folder... not really. With Papirus it's even worse.

A possible workaround is to use a dark icon theme (Qogir Dark, Papirus Dark...), but then all icons take on light hues and are therefore not visible on the main panel's white background (as is the case for Matcha Light and "plain" Matcha"). Which means I also have to use Match Dark, and I don't want a fully dark theme...

I reckon Thunar had similar panel issues so would it be possible to fix Nemo too? I surmise Caja may have the same problem.

Otherwise the theme looks gorgeous. Keep on the good work, and thanks again.

**Comment by vinceliuice** [comment]
Thanks! I’ll check this, if necessary I’ll make the dark sidebar to be light.

**Comment by Magean0** [comment]
Wow, that was a fast reply! Thanks!

**Comment by vinceliuice** [comment]
I fixed this, you can try the last update!

**Comment by Magean0** [comment]
Nice work! My thanks :-)

**Comment by vinceliuice** [comment]
You are welcome!
