### ISSUE TITLE
gnome-shell status menu transparency issue - Matcha-dark-sea

### ISSUE THREAD

**Issue by kwheelans** [vinceliuice/Matcha-gtk-theme#110]
Pop!_OS 19.10 x86_64
Gnome version: 3.34

The all menu areas like the GNOME status menu have large transparent areas when Matcha-dark-sea is used for shell appearance when display scaling is used.  This issue does not happen when Matcha-dark-aliz or Matcha-dark-azul.

<h3>Examples</h3>
<h4>Matcha-dark-sea</h4>

![Shell-4k-2x_scaling-matcha-dark-sea](https://user-images.githubusercontent.com/57738230/78841974-c72b1480-79cc-11ea-9a66-3129f039f20f.png) 

<h4>Matcha-dark-aliz</h4>

![Shell-4k-2x_scaling-matcha-dark-aliz png](https://user-images.githubusercontent.com/57738230/78841990-d14d1300-79cc-11ea-8de2-09b121585e26.png)

**Comment by vinceliuice** [comment]
Does this happen after you reboot you system?

**Comment by kwheelans** [comment]
Found that the issue is fixed after rebooting. Issue looks like it is only cause when the laptop is plugged into an external monitor after booting without the monitor plugged in.  Don't think this is an issue with the theme so I will close.  Thanks.
