### ISSUE TITLE
just a quick question

### ISSUE THREAD

**Issue by clumsyfingers** [vinceliuice/Matcha-gtk-theme#117]
im just editing matcha a bit for my own use, and i really dont like the tiny grey top border around windows - see https://i.imgur.com/LSId8Wy.png

i would like to color it like the rest of the titlebar/headerbar, but i just cant work out which setting in the grk.css i should be editing
can you tell me which?
thanks :)

**Comment by vinceliuice** [comment]
Find line 32 of /src/gtk-3.0/sass/_colors.scss
change  `$highlight: if($variant =='light', rgba(white, 0.13), rgba(white, 0.10));` to `$highlight: if($variant =='light', rgba(white, 0), rgba(white, 0));`
then run `./parse-sass.sh` , after that you can install this
