### ISSUE TITLE
Visual glitches while searching in GNOME overview

### ISSUE THREAD

**Issue by jantomicky** [vinceliuice/Matcha-gtk-theme#129]
While searching for things in GNOME overview on Manjaro, these visual glitches happen (different size and location every time):

![matcha-issue-gnome-overview-search](https://user-images.githubusercontent.com/41518085/88464118-84784400-ceb8-11ea-83af-53acf5546f1c.png)

Tried this on a fresh VM installation. Unfortunately I have no set of steps to reproduce this a 100%, but the glitches happen often enough, just try and type/delete/type quickly.

**Comment by vinceliuice** [comment]
Could you tell me you manjaro version and GPU device?

**Comment by jantomicky** [comment]
Kernel 5.7.9-1-MANJARO
Radeon RX Vega (VEGA10, DRM 3.37.0, 5.7.9-1-MANJARO, LLVM 10.0.0) / AMD ATI Radeon RX Vega 56/64
GNOME 3.36.4

Unfortunately I don't know how to get precise Manjaro version, all output just says "rolling", I am fully up to date though.

I have also found this thread https://forum.manjaro.org/t/graphical-glitches-in-gnome-launcher/137752 with a recorded demo https://www.youtube.com/watch?v=JtGYsRpZ7PE

Let me know if I can help in any other way, thanks!

**Comment by vinceliuice** [comment]
I updated this theme, could you test it for me, because I don't find this issue on my computer so I don't know if it's fixed or not.

**Comment by jantomicky** [comment]
Gladly, thank you! I've downloaded the latest code and installed the theme as "MatchaDev", then switched the themes and (just to be sure) restarted the VM. Unfortunately the issue is still present.

I can see the latest commit, I'll take a look, maybe I'll come up with a pull request.

**Comment by vinceliuice** [comment]
I don't know what caused this issue, if I can't find the reason, then I can only rewrite it based on the latest adwaita theme.

**Comment by jantomicky** [comment]
I think I might have found the cause of the issue, see this line: https://github.com/vinceliuice/Matcha-gtk-theme/blob/master/src/gnome-shell/sass/_common.scss#L2213

When I remove it, the search results become wider, yes, but the issue is gone. Also the "glitches" or "artifacts" always seem to be of the same width as the horizontal padding that is set on that line, i.e. I reduced the padding to 48px and the glitches became narrower as well.

![gnome-matcha-search-glitches-narrow](https://user-images.githubusercontent.com/41518085/88480900-f56f3880-cf58-11ea-9cb4-4a556c49cc19.png)

**Comment by vinceliuice** [comment]
Thanks, that's great!
