### ISSUE TITLE
GNOME system tray text is dark in some places when dark shell theme is used (all color variants).

### ISSUE THREAD

**Issue by TechnologyMan101** [vinceliuice/Matcha-gtk-theme#135]
I am using GNOME 3.36. My system menu text is black in some places when they are supposed to be white. I am using the dark shell theme. This happens with all color variants. This does not happen when my cursor is still on the affected text though.

Please see screenshots below:
![Screenshot from 2020-09-27 17-25-13](https://user-images.githubusercontent.com/65311278/94379637-98be0480-00e6-11eb-90bf-c08b8e141573.png)

![Screenshot from 2020-09-27 17-25-31](https://user-images.githubusercontent.com/65311278/94379640-9bb8f500-00e6-11eb-8d83-7b885ad7aa9f.png)

![Screenshot from 2020-09-27 17-25-48](https://user-images.githubusercontent.com/65311278/94379647-a1163f80-00e6-11eb-9a06-87653f0fafdc.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by TechnologyMan101** [comment]
For whenever you fix this, how is the process for updating the theme? Do I delete the theme, then run the script, or just run the script again?

This may be a question that I probably won't use the answer for this time because I am thinking of reinstalling my system too.

**Comment by vinceliuice** [comment]
Just run the script again! it'll replace the old files

**Comment by TechnologyMan101** [comment]
Thank you for the clarification! I have another question too. Is there a way to make the theme install to `/usr/share/themes/`? It would be very convenient if I could do that without having to manually copy the theme files.

**Comment by vinceliuice** [comment]
Just run the script with sudo! `sudo ./install.sh`

**Comment by TechnologyMan101** [comment]
Thank you very much for your help!

I look forward to the bug fix!

**Comment by TechnologyMan101** [comment]
I just noticed that you pushed the bug fix out. It works perfectly now!

Thank you very much for the very quick bug fix!
