### ISSUE TITLE
Calendar Selection (Notification Area) Hard To Differentiate From Current Day (All Shell Themes)

### ISSUE THREAD

**Issue by TechnologyMan101** [vinceliuice/Matcha-gtk-theme#137]
As you can see in the screenshot below, it is hard to differentiate the selected date from the current date. Also, the current date's number disappears.

Matcha Shell Themes (Selected is 14 Oct and current is 3 Oct. Current date is invisible. Colors are the same for both making it hard to differentiate them. All Matcha Shell themes have this problem):
![Screenshot from 2020-10-03 23-27-11](https://user-images.githubusercontent.com/65311278/95008584-fd3dff80-05cf-11eb-869f-ab2033f7bc21.png)

Stock GNOME Shell Theme AKA Adwaita (Same dates. Current date is not invisible and colors are different making the two dates easy to differentiate. Only dark as default Adwaita does not have a light shell theme.):
![Screenshot from 2020-10-03 23-36-44](https://user-images.githubusercontent.com/65311278/95008788-d1237e00-05d1-11eb-9a15-e1d3c90784bd.png)

Pop!_OS Shell Theme (Same dates. Current date is not invisible and colors are different making the two dates easy to differentiate. Same across dark and light.):
![Screenshot from 2020-10-03 23-32-27](https://user-images.githubusercontent.com/65311278/95008765-ac2f0b00-05d1-11eb-96d1-d91e31943f2e.png)

Ubuntu Yaru Shell Theme (Same dates. Current date is not invisible and colors are different making the two dates easy to differentiate. Same across dark and light.):
![Screenshot from 2020-10-03 23-50-13](https://user-images.githubusercontent.com/65311278/95009202-11383000-05d5-11eb-9f1c-0dbd16170eae.png)

**Comment by TechnologyMan101** [comment]
UPDATE: If on Matcha, the current date does not disappear if there are no events on that particular day.

**Comment by vinceliuice** [comment]
Fixed!
