### ISSUE TITLE
Gnome Shell 3.38 - Calendar Events is not styled

### ISSUE THREAD

**Issue by remissio** [vinceliuice/Matcha-gtk-theme#139]
Using Matcha-dark-azul the Gnome Shell 3.38 Update is missing styles for the "Events" Area.

![image](https://user-images.githubusercontent.com/34125671/96217030-122c7280-0f82-11eb-8920-b0236ab73dcc.png)

**Comment by vinceliuice** [comment]
I'll fix this!
