### ISSUE TITLE
Transparent space on save as pop up

### ISSUE THREAD

**Issue by josedr120** [vinceliuice/Matcha-gtk-theme#140]
Been a while with this bug, happens on all programs on maximixed.

![issue_bug_matcha-theme](https://user-images.githubusercontent.com/43816065/97785544-16f54700-1b7c-11eb-8084-da52186f96e9.png)

**Comment by themew** [comment]
Wanted to add to this, how do we move the SAVE and CANCEL buttons back to the bottom of the window?

**Comment by vinceliuice** [comment]
Firefox bug, not theme issue
