### ISSUE TITLE
Events overflow - Gnome Shell 3.38.2

### ISSUE THREAD

**Issue by albertaparicio** [vinceliuice/Matcha-gtk-theme#144]
I am running Manjaro with Gnome Shell 3.38.2. A while ago I noticed that the Events section in the Notifications Center would overlap with the World Clock section when there were more than 5 events in a single day.

Just to see if the error was at theme or gnome-shell level, I checked what happened in the same situation with the default Manjaro theme, and I see that all the sections below the calendar scroll if there are too many elements to fit. I also checked all versions of the shell theme (namely, matcha, matcha-azul, matcha-aliz and its dark versions) and the issue is present in all of them.

I just updated Matcha-gtk-theme to the latest version (`2020-12-25` at the time of writing) and I see that the issue is still present.

Here are some screenshots of this situation:

When there are less than 5 events in Matcha:
![2_Events](https://user-images.githubusercontent.com/8900814/103414597-eaab7600-4b7e-11eb-9b1d-c9f9bac70ed3.png)

Less than 5 events in the default theme:

![2_events_default](https://user-images.githubusercontent.com/8900814/103414610-f72fce80-4b7e-11eb-9bc8-3aaeb8666006.png)

More than 5 events in Matcha:

![7_events](https://user-images.githubusercontent.com/8900814/103414628-01ea6380-4b7f-11eb-930c-cc2c78d4510d.png)

More than 5 events in the default theme:

![7_events_default](https://user-images.githubusercontent.com/8900814/103414636-07e04480-4b7f-11eb-916d-287da67a5e47.png)

In the default theme the Events, World Clock and Weather Section are one scrollable section:

![7_events_default_scroll](https://user-images.githubusercontent.com/8900814/103414652-16c6f700-4b7f-11eb-95da-ec8fde680823.png)

**Comment by vinceliuice** [comment]
Thanks for this, I'll fix that
