### ISSUE TITLE
GNOME Shell - Excess events cut into other info boxes

### ISSUE THREAD

**Issue by Electw** [vinceliuice/Matcha-gtk-theme#147]
![image](https://user-images.githubusercontent.com/55963122/104407507-94dbb400-5516-11eb-9cfa-90614eaae3ce.png)
![image](https://user-images.githubusercontent.com/55963122/104407520-9b6a2b80-5516-11eb-96be-610aa60c9778.png)

To reproduce:
Create a large number of events on a separate date. Click on that date in the notifications panel, and the text will be overflowing.

Expected result:
The info boxes below are pushed down and the entire part is made scrollable, just like in Adwaita.

Other info:
GNOME Shell 3.38
Manjaro 20.2

**Comment by vinceliuice** [comment]
I fixed this at last update on github,

**Comment by vinceliuice** [comment]
The manjaro software mirror will take time to update

**Comment by Electw** [comment]
Installed the version from GitHub and it looks great! Thank you!
![image](https://user-images.githubusercontent.com/55963122/104435316-17796900-5541-11eb-9297-44f0f2266554.png)
