### ISSUE TITLE
ibus panel display error when using Matcha theme

### ISSUE THREAD

**Issue by CrSjimo** [vinceliuice/Matcha-gtk-theme#152]
The background of ibus panel become transparent when inputting in a window using theme Matcha-azul-dark(both minimum and maximum):

![display error in a maximum window](https://img.imgdb.cn/item/601b8d8b3ffa7d37b34d83e7.png)

![display error in a minimum window](https://img.imgdb.cn/item/601b8d8b3ffa7d37b34d83fe.png)

And it works normally when using another theme (Adwaita-maia-dark)

![](https://img.imgdb.cn/item/601b8d8b3ffa7d37b34d83f6.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
已经修复了！
