### ISSUE TITLE
May I publish the different Matcha theme variants on flathub?

### ISSUE THREAD

**Issue by Mek101** [vinceliuice/Matcha-gtk-theme#153]
I made the manifest for Matcha dark sea already https://github.com/mek101/flathub/tree/org.gtk.Gtk3theme.Matcha-dark-sea, the others are soon to come

**Comment by vinceliuice** [comment]
Thanks!

**Comment by Mek101** [comment]
All up and published!

**Comment by vinceliuice** [comment]
Thank you!

**Comment by Mek101** [comment]
I'm adding the new pueril variant
