### ISSUE TITLE
How change matcha-dark-sea colour scheme xfce

### ISSUE THREAD

**Issue by mixalis1987** [vinceliuice/Matcha-gtk-theme#156]
How do we change just the colours of the theme?
Like the loading bar and insens sliders and insense buttons. "The darker shade of green on buttons we cant interact with"

Watch the video to see my issue: https://youtu.be/YekBWNWbm0M

**Comment by vinceliuice** [comment]
You need to change the progress color

**Comment by mixalis1987** [comment]
> You need to change the progress color

What css file do i need to edit and what line of code?

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Matcha-gtk-theme/blob/a31abf0da98fa2b8e7f87364249b069416d10671/src/gtk-3.0/sass/_colors.scss#L50

**Comment by mixalis1987** [comment]
> https://github.com/vinceliuice/Matcha-gtk-theme/blob/a31abf0da98fa2b8e7f87364249b069416d10671/src/gtk-3.0/sass/_colors.scss#L50

Thanks for the reply but that's not working. I need the the green slider and button in the pavucontrol changed, but I can't find it.

**Comment by mixalis1987** [comment]
Used my own css in .config/gtk-3.0/ and it picked up the changes i previously made.
