### ISSUE TITLE
Gnome40

### ISSUE THREAD

**Issue by aniketfuryrocks** [vinceliuice/Matcha-gtk-theme#157]
Gnome40 is out, most people have already upgraded. This theme works well but hinders the UX on the dockside of things, Would love to see Gnome40 support.

**Comment by vinceliuice** [comment]
It's already suported

**Comment by vinceliuice** [comment]
I finished it yestoday

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Matcha-gtk-theme/commit/5b6193d639e4eec061bbd3c038c4447110313a06
