### ISSUE TITLE
Bad contrast in GNOME Calendar with matcha-dark-sea

### ISSUE THREAD

**Issue by TastyPi** [vinceliuice/Matcha-gtk-theme#160]
GNOME Calendar has poor contrast in its events when using matcha-dark-sea (and possibly the other dark variants, I didn't check).

[This thread](https://www.reddit.com/r/gnome/comments/ldd8pu/bad_contrast_in_gnome_calendar_how_to_fix_it/gm7yod6) suggests it's fixable by setting the `color` for `event.color-light` and `event.color-dark`.

Screenshot of the issue:
![screenshot of gnome calendar](https://i.imgur.com/PzAWV5i.png)

**Comment by vinceliuice** [comment]
Fixed!
