### ISSUE TITLE
Background not rendered correctly in Gnome Terminal

### ISSUE THREAD

**Issue by mcnesium** [vinceliuice/Matcha-gtk-theme#163]
![gt-screenshot](https://user-images.githubusercontent.com/476060/115703910-f8be1600-a36a-11eb-9cd2-87c70f5d60e3.png)

Gnome Terminal behaves odd when using this theme, while having it set to *use colors from system theme*:

<img src="https://user-images.githubusercontent.com/476060/115703640-a5e45e80-a36a-11eb-98aa-ccdd2251e2ae.png" width="33%" height="33%"/>

This is probably related to [this issue](https://gitlab.gnome.org/GNOME/vte/-/issues/284), where [the author states](https://gitlab.gnome.org/GNOME/vte/-/issues/284#note_1066649)
> […] but really the theme authors need to fix it on their side.

    # GNOME Terminal 3.40.0 using VTE 0.64.0 +BIDI +GNUTLS +ICU +SYSTEMD

**Comment by vinceliuice** [comment]
Did you install the theme from github?

**Comment by mcnesium** [comment]
Yes, but failed to merge correctly. Sorry
