### ISSUE TITLE
Revert to flat top bar hover effects

### ISSUE THREAD

**Issue by mcnesium** [vinceliuice/Matcha-gtk-theme#164]
Recently Gnomes Adwaita changed the look of their top bar elements to being round. Please revert this to the original flat look:

![sc_adw](https://user-images.githubusercontent.com/476060/115737216-3717fd00-a38c-11eb-8ad6-ce41666339af.jpg)

This theme inherits this and looks like that now:

![sc_round](https://user-images.githubusercontent.com/476060/115735424-c15f6180-a38a-11eb-997d-f0740cbfffee.png)

Since one of the features of this theme was to be flat and not cheesy. So could you please revert the look of the top bar to this:

![sc_flat](https://user-images.githubusercontent.com/476060/115735394-bc9aad80-a38a-11eb-8a2b-d2442f58ff88.png)

**Comment by vinceliuice** [comment]
Did you install this theme from here (last update) ? because gnome-shell 40.0 is supported now, and this is fixed

**Comment by mcnesium** [comment]
Yes I did. But I missed to merge correctly. Sorry. :facepalm: 
And thank you for fixing this!

Is it possible to remove the 1px border around the hover elements?

![screenshot](https://user-images.githubusercontent.com/476060/115740771-73009180-a38f-11eb-8f8a-f83f9dd0b85d.png)

**Comment by vinceliuice** [comment]
You need to reinstall this theme by run ./install.sh

**Comment by mcnesium** [comment]
I know, I did.

Now it's only the date element that still has rounded corners when hovering in closed state (not when hovering with opened menu).

**Comment by vinceliuice** [comment]
Fixed!
