### ISSUE TITLE
Why overriding GTK scrollbar colors for Firefox?

### ISSUE THREAD

**Issue by emilio** [vinceliuice/Matcha-gtk-theme#167]
I noticed that with this theme scrollbar active thumb color is different from other GTK apps in Firefox Nightly / beta. I thought it was a bug in Firefox, but I tracked it down to this chunk of code (among other similar ones):

https://github.com/vinceliuice/Matcha-gtk-theme/blob/ae779bc200decbb801ad4ccae0f441d31b11b9bd/src/gtk/gtk-3.0/gtk-dark-azul.css#L6654-L6664

So it looks intentional. I was only wondering why, as blame didn't quite reveal an answer :)

**Comment by vinceliuice** [comment]
I'll removed it

**Comment by emilio** [comment]
Ah, sure, sounds good to me, thanks! I was mostly curious, not opposed to that behavior, but less code is always better if possible, of course :)
