### ISSUE TITLE
Change color of classic application header bars

### ISSUE THREAD

**Issue by mcnesium** [vinceliuice/Matcha-gtk-theme#169]
What do I need to adjust to change the color of classic Gnome application header bars like Evolution or Gimp, as well as Electron apps like VSCodium? They are still rendered dark in the light theme:

![Screenshot from 2021-05-27 15-22-48](https://user-images.githubusercontent.com/476060/119835992-a50e9180-bf01-11eb-969b-f873d4cc3d18.png)

**Comment by FreaxMATE** [comment]
For me Matcha light themes do have a light bar:

![Screenshot at 2021-06-04 13-51-33](https://user-images.githubusercontent.com/49864414/120802627-f098ef00-c542-11eb-912e-49ac4d322d82.png)

**Comment by vinceliuice** [comment]
Just restart your desktop!
