### ISSUE TITLE
Support for cinnamon's cinnamenu applet.

### ISSUE THREAD

**Issue by fredcw** [vinceliuice/Matcha-gtk-theme#178]
The class .menu-category-button-hover{} in cinnamon.css is only used by cinnamenu applet but at the moment it's bright red.

```
.menu-category-button-hover {
  background-color: red;
  border-radius: 2px;
}
```

![Screenshot from 2021-07-10 15-16-24](https://user-images.githubusercontent.com/58893963/125166368-47719400-e193-11eb-9c77-625639fa8766.png)

I have included a temporary fix in cinnamenu for all the Matcha themes which I will remove if/when the themes are fixed. To temporarily remove the fixes from cinnamenu, just delete the lines in the applet's buttons.js file that contain "Matcha".

Thanks.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by fredcw** [comment]
Thanks.
