### ISSUE TITLE
Problem with icon Manjaro/GNOME

### ISSUE THREAD

**Issue by S0ftwareTester** [vinceliuice/Matcha-gtk-theme#190]
Hello, 

when I changed the theme (shell) in the login screen from Adwaita to Matcha-dark-sea there was a problem with the icon when i want selection of workspaces, preview in the attached pictures, the themes are great, one of the best polished if not the best. However, there was a drawback that I noticed. There was one more problem with the firefox theme, it looks as if the icons have a scaling problem.

Firefox 94.0.2
GNOME Shell 41.1
Manjaro
Kernel 5.10.79-1-MANJARO
Matcha-dark-sea 

Yours faithfully.

![Icon_Problem](https://user-images.githubusercontent.com/95168225/143764962-4efcc794-fdc8-4780-ac70-1435f13b127f.png)
![Icon_problemA](https://user-images.githubusercontent.com/95168225/143764969-141a8b78-fc1f-4977-8927-1d467d7000f8.png)

![obraz](https://user-images.githubusercontent.com/95168225/143765348-902c0a27-36a5-41f9-8902-efe1818db17f.png)
![obraz](https://user-images.githubusercontent.com/95168225/143765388-a5908416-6da2-4d98-8660-48ed78e7c021.png)

**Comment by vinceliuice** [comment]
Fixed!

**Comment by S0ftwareTester** [comment]
Right, now looks perfect !
![Zrzut ekranu z 2021-11-28 22-16-58](https://user-images.githubusercontent.com/95168225/143786294-e7bccad7-23d9-4d00-beb3-ec46c5f1ea69.png)

What about with Firefox icons ? 
Add new card, refresh, go to the previous page, go to next page, application menu, more tools and close tabs.
Will you work on it?
I don't know whether to wait or think about changing the theme.

**Comment by vinceliuice** [comment]
Firefox issues fixed!

**Comment by S0ftwareTester** [comment]
Right now looks perfect ! :).|
Good job.
![Zrzut ekranu z 2021-11-29 14-08-19](https://user-images.githubusercontent.com/95168225/143874163-6eef3dd6-1b17-4a6c-8049-0fa891e536b2.png)

**Comment by vinceliuice** [comment]
You are welcome!
