### ISSUE TITLE
text hard to see in GNOME calendar app

### ISSUE THREAD

**Issue by alex-tee** [vinceliuice/Matcha-gtk-theme#193]
I'm using Matcha dark pueril and this is what I see for my events in GNOME calendar:

![Screenshot from 2021-12-24 13-54-14](https://user-images.githubusercontent.com/3407655/147357410-c4141bf9-4d72-4c05-a2ac-ae2234ed2f55.png)

**Comment by vinceliuice** [comment]
Fixed!
