### ISSUE TITLE
text in current line hard to see in GNOME text editor

### ISSUE THREAD

**Issue by alex-tee** [vinceliuice/Matcha-gtk-theme#198]
I am currently on Matcha theme 2021.12.25 using Matcha-dark-pueril on Arch Linux

The text is hard to see on the current line:

![Screenshot from 2022-01-11 16-37-02](https://user-images.githubusercontent.com/3407655/148983600-853fb251-016f-412b-b8ae-550a07ed0c77.png)

**Comment by vinceliuice** [comment]
Change the gedit colorscheme

**Comment by alex-tee** [comment]
oh I'm sorry I thought it inherited the theme from GTK! it looks like I used tango
