### ISSUE TITLE
Selection highlight colour is inconsistent across apps

### ISSUE THREAD

**Issue by frost19k** [vinceliuice/Matcha-gtk-theme#212]
I installed Matcha from the git repo with:

```Bash
❯ git clone https://https://github.com/vinceliuice/Matcha-gtk-theme.git
❯ cd Matcha-gtk-theme
❯ sudo ./install -c dark -t sea --gdm
❯ cp -rfL /usr/share/themes/Matcha-dark-sea/gtk-4.0 -t ~/.config
```
As you can see in the screenshots below, the highlight colour is different across apps. 

Is it an issue with the theme and/or `libadwaita` or have I misconfigured something?

![gnome-tweaks](https://user-images.githubusercontent.com/49780407/205812681-c4102f82-7169-419b-aea2-923cae060249.png)

![gnome-settings](https://user-images.githubusercontent.com/49780407/205812672-2b3ba0d3-a301-4e52-a429-9dcf52b09dee.png)

![nautilus](https://user-images.githubusercontent.com/49780407/205812684-38a94817-7320-44fc-8b68-bbc6a69ce375.png)

**Comment by vinceliuice** [comment]
I do not fixed Libadwaita issues yet

**Comment by frost19k** [comment]
Oh, okay. 

It sounds like you're on it so I wouldn't mind if you wanted to close this issue.

**Comment by vinceliuice** [comment]
Never mind, I'll close it when I fixed

**Comment by frost19k** [comment]
Closing as it's been fixed in the latest update.

You also fixed the issue where the title bar was a different width when there's a toggle (in gnome settings).

This is my favourite theme again. Thank you so much!
