### ISSUE TITLE
Firefox theme needs to be updated

### ISSUE THREAD

**Issue by Dejweed** [vinceliuice/Matcha-gtk-theme#219]
There are also some mistakes in **userChrome.css** importing `Qogir` instead of `Matcha`

Keep up the good work :)

**Comment by Dejweed** [comment]
Nice work, but I think it could be improved further. Here are some things I've noticed:

- Button radius and context menu margins don't match the gtk3 theme
- GTK3 apps don't have the top line when tiled or maximized, firefox does
- The green URL bar outline as seen in the [preview](https://github.com/vinceliuice/Matcha-gtk-theme/raw/master/src/extra/firefox/preview.png?raw=true) is missing

![image](https://github.com/vinceliuice/Matcha-gtk-theme/assets/65261588/1be6ea9d-ee9f-4ea8-8077-143b14aeb5e0)


- Inactive hovered close button 
![image](https://github.com/vinceliuice/Matcha-gtk-theme/assets/65261588/2d040a86-1cb3-4f79-9e7b-16b6e9bcca0f)

- New tab and list all tabs buttons aren't vertically centered
![image](https://github.com/vinceliuice/Matcha-gtk-theme/assets/65261588/747631e8-1afe-4fa3-bc86-df2ea5ec5123)

- The URL bar gets shifted just a little bit when clicked (here I am clicking on the urlbar and then pressing ESC)
![url](https://github.com/vinceliuice/Matcha-gtk-theme/assets/65261588/b32fef00-965e-44b4-a138-58861ab4e63e)


- It would be awesome if the colors would follow the gtk theme and change when using aliz,azul... Here's how it currently looks with matcha-dark-aliz:
![image](https://github.com/vinceliuice/Matcha-gtk-theme/assets/65261588/d3a7aa69-6d2c-4c27-8af7-f5f9c5606eaf)

Also unrelated to firefox theme, it would probably be smart to change the naming, moving the `light` or `dark` to the end, so from **Matcha-dark-aliz** to **Matcha-aliz-dark** and so on.

**Comment by GaucovyAero** [comment]
i have a weird border around the webpage when firefox is in fullscreen
![image](https://github.com/vinceliuice/Matcha-gtk-theme/assets/85581164/14953b1e-da78-4b74-9a94-c41770c50ad7)
