### ISSUE TITLE
Gnome Panel Status menu  doesn't have right arrow or down (after click) arrow icon 

### ISSUE THREAD

**Issue by ceyhunn** [vinceliuice/Matcha-gtk-theme#34]
Gnome Panel Status menu  doesn't have right arrow or down (after click) arrow icon on list. This icon indicates that menu has submenus.

**Comment by vinceliuice** [comment]
I removed all arrows on panel

**Comment by ceyhunnabiyev** [comment]
Why? Arrow indicates that menu is clickable. You removed all arrows, it means that we don't know which menu has submenu,
