### ISSUE TITLE
Title bar bold font

### ISSUE THREAD

**Issue by AtifChy** [vinceliuice/Matcha-gtk-theme#83]
how do I enable bold font in title bar?
![Screenshot from 2019-12-01 13-11-29](https://user-images.githubusercontent.com/42291930/69910850-5a12db80-143c-11ea-9330-c398ab81da89.png)

**Comment by dionweb** [comment]
Edit ~/.config/gtk-3.0/gtk.css and add the next rule:

`headerbar {
    font-weight: bold;
}`
