### ISSUE TITLE
Slightly different button colors in Nautilus modals' titlebars

### ISSUE THREAD

**Issue by jakubzet** [vinceliuice/Matcha-gtk-theme#94]
Hi there! First of all, thank you for marvelous your job!
As for the issue - I recently noticed that in every variant of theme (Sea/Aliz/Azul), the bg color of the action button (Zapisz is Save in polish) in the title bar is standing out. Did you happen to see those on your desktops too? I'm using Manjaro Linux / GNOME 3.34.4

![image](https://user-images.githubusercontent.com/3542512/75697767-d7552300-5cad-11ea-852c-f0b43d757b11.png)

**Comment by vinceliuice** [comment]
Suggestion button is different from normal one

**Comment by jakubzet** [comment]
I wasn't sure if that's intended. That solves the issue, then! :)
