### ISSUE TITLE
update light variant for xfce 4.14

### ISSUE THREAD

**Issue by denikris** [vinceliuice/Matcha-gtk-theme#95]
hi,
i'm using xubuntu 19.10 with [dockbarx](https://github.com/M7S/dockbarx) [plugin](https://github.com/TiZ-EX1/xfce4-dockbarx-plugin) in xfce panel which is gtk 2.x, i installed it via [ppa](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx) and using Qogir(not Qogir-dark) as icon theme

this is azul standard variant which is everything look fine (dark variant with Qogir-dark looks fine too)
![Screenshot_2020-03-10_20-29-38](https://user-images.githubusercontent.com/16707606/76317263-7f9e6380-630e-11ea-8bc5-8cb7fd7335e1.png)

and this is light variant which have white background on dockbarx but the rest are dark and icons+texts are dark on dark which make them hard to read, and xfwm4 theme for light and standard is same color (i assume it should be white because menubar color in gtk 2.x and 3.x apps is white)
![Screenshot_2020-03-10_20-29-00](https://user-images.githubusercontent.com/16707606/76317544-ef145300-630e-11ea-94f3-6ba642a6d36d.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed！
