### ISSUE TITLE
Gnome 3.36 broke the shell theme

### ISSUE THREAD

**Issue by kouros17** [vinceliuice/Matcha-gtk-theme#96]
I'm using manjaro and the updates of gnome 3.36 broke the shell theme. 
The calendar's color has changed.

![Screenshot](https://user-images.githubusercontent.com/27904795/76361441-baf95c00-6327-11ea-8944-b94d65ebf596.png)

**Comment by vinceliuice** [comment]
I'll fix it!

**Comment by vinceliuice** [comment]
Fixed!
