### ISSUE TITLE
Dots on Application-Overview buggy

### ISSUE THREAD

**Issue by Rioluuu** [vinceliuice/Matcha-gtk-theme#98]
When clicking on the dots on the right of the overview, they start bugging.
![Bildschirmfoto von 2020-03-14 11-36-15](https://user-images.githubusercontent.com/43097559/76680423-954eaa00-65e8-11ea-8f85-db429d5359fd.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed
