### ISSUE TITLE
Matcha theme on gnome 3.36 issue

### ISSUE THREAD

**Issue by JinnerAtumia** [vinceliuice/Matcha-gtk-theme#99]
So I received the 20200313 update of Matcha theme to support gnome 3.36, everything looks good except the "Open Window" text. Is this a gnome bug or the theme?
![Screenshot from 2020-03-16 07-12-25](https://user-images.githubusercontent.com/52413540/76713874-49217800-6756-11ea-86ae-c9974680de5f.png)

**Comment by vinceliuice** [comment]
This is a gnome bug, I'll try update the style to make this looks better

**Comment by vinceliuice** [comment]
Fixed！
